// Do not edit this file manually, it's configured by CMake. The version numbers are set in SCVersion.txt
+ Main {
    *scVersionMajor { ^3 }
    *scVersionMinor { ^6 }
    *scVersionPostfix { ^".2" }
}

